Ft add acados planner
maxspahn/localPlannerBench pull request #43
Opened 2022-08-17 08:32 UTC by c-salmi

Adds a simple point mass acados planner.

To test:
- Install acados_template as instructed [here](https://github.com/acados/acados/tree/master/interfaces/acados_template)
- Go to `cd experiments/1_fabric_mpc/pointMass`
- Run `runner -c setup/exp.yaml -p setup/acados_mpc.yaml --render`

2022-08-17 19:32 UTC, maxspahn commented
Great work. The installation was very smooth. 
You can even install it by adding it to the `pyproject.toml` using `poetry add <path-to-acados-template>.

However, I realized that randomized goals cannot be respected. 

`runner -c setup/exp.yaml -p setup/acados_mpc.yaml --random-obst` 

still uses the not-randomized obstacles.

I will further investigate that.

2022-08-17 19:42 UTC, maxspahn requested changes
Amazing, @c-salmi!

I think we should make this solver symbolic for obstacles, goal and initial positions so that it can deal with randomized scenarios.

Additionally, i think many of the printouts can be removed. 
You could consider using `logging.debug` to not loose the value of some of these printouts.

2022-08-18 06:00 UTC, maxspahn commented on plannerbenchmark/planner/acadosMpc/pointMassModel.py
> +    obs_pos = np.array(exp.obstacles()[0].position())
Actually only line 41 is important for that comment.

2022-08-19 11:43 UTC, c-salmi commented
Still did not manage to make the start, goal and obs symbolic The way to do this in acados is not yet clear to me. But it does now work with random static obstacles and goals.

The problem was in the `__init__` function of the Planner class. There I used the `exp.Obstacles()` function of the Experiment class to get the info of the obstacles. However when random obstacles are requested, this function will not yet return the correct obstacles. Only when calling `exp.Obstacles()` at a later stage (like in `computeAction`) will it return the random obstacles. 

For now I moved the initialization of the planner to the first call to `computeAction`.

2022-08-26 07:46 UTC, merged